stages:
  - build
  - test
  - test_part_2
  - test_part_3

docker-build-master:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

test1:
  image: registry.gitlab.com/smeetsee/it/spin-docker
  stage: test
  script:
    - rm -rf .git
    - git clone https://github.com/nimble-code/Spin.git
    - cd Spin/Examples
    - spin hello.pml
    - spin -T hello.pml

test2:
  image: registry.gitlab.com/smeetsee/it/spin-docker
  stage: test
  script:
    - rm -rf .git
    - git clone https://github.com/nimble-code/Spin.git
    - cd Spin/Examples
    - spin -a loops.pml
    - cc -DNOREDUCE -o pan pan.c
    - ./pan
  artifacts:
    paths:
      - Spin/Examples/pan

test3:
  image: registry.gitlab.com/smeetsee/it/spin-docker
  stage: test_part_2
  needs:
    - job: test2
      artifacts: true
  script:
    - cd Spin/Examples
    - ./pan -a
  artifacts:
    paths:
      - Spin/Examples/loops.pml.trail

test4:
  image: registry.gitlab.com/smeetsee/it/spin-docker
  stage: test_part_3
  needs:
    - job: test3
      artifacts: true
  script:
    - git clone https://github.com/nimble-code/Spin.git tmp
    - mv tmp/Examples/loops.pml Spin/Examples/loops.pml
    - rm -rf tmp
    - cd Spin/Examples
    - spin -t -p loops.pml

test5:
  image: registry.gitlab.com/smeetsee/it/spin-docker
  stage: test
  script:
    - rm -rf .git
    - git clone https://github.com/nimble-code/Spin.git
    - cd Spin/Examples
    - spin -a loops.pml
    - cc -DNP -DNOREDUCE -o pan pan.c
    - ./pan -l

test6:
  image: registry.gitlab.com/smeetsee/it/spin-docker
  stage: test
  script:
    - rm -rf .git
    - git clone https://github.com/nimble-code/Spin.git
    - cd Spin/Examples
    - spin -a leader0.pml

test7:
  image: registry.gitlab.com/smeetsee/it/spin-docker
  stage: test
  script:
    - rm -rf .git
    - git clone https://github.com/nimble-code/Spin.git
    - cd Spin/Examples
    - spin -o6 -p -g -u10000 priorities.pml

test8:
  image: registry.gitlab.com/smeetsee/it/spin-docker
  stage: test
  script:
    - rm -rf .git
    - git clone https://github.com/nimble-code/Spin.git
    - cd Spin/Examples
    - spin -f "[] ( p U ( <> q ))"
